name:                smt-lsp
version:             0.1.0.0
github:              "githubuser/smt-lsp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/smt-lsp#readme>

default-extensions:
- BangPatterns
- DeriveAnyClass
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- EmptyDataDeriving
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- PartialTypeSignatures
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- mtl
- sexpresso
- text

library:
  source-dirs: src

executables:
  smt-lsp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smt-lsp

tests:
  smt-lsp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smt-lsp
